apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-books
  namespace: {{ .Release.Namespace }}
  labels:
    type: "{{ .Values.name }}-books"
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.nfs.storageCapacity | quote }}
  accessModes:
    - {{ .Values.nfs.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.nfs.nfsServer }}
    path: {{ .Values.nfs.nfsPath | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-books
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: ""
  selector:
    matchLabels:
      type: "{{ .Values.name }}-books"
  accessModes:
    - {{ .Values.nfs.accessMode }}
  resources:
    requests:
      storage: {{ .Values.nfs.storageCapacity | quote }}
