apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.debugging.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.debugging.serviceName }}
spec:
  selector:
    app: {{ .Values.debugging.serviceName }}
  ports:
    - name: http
      port: {{ .Values.debugging.port }}
