apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.consensusClient.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.consensusClient.name }}
  ports:
    - name: p2p-tcp
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: p2p-udp
      port: 9000
      targetPort: 9000
      protocol: UDP
    - name: api
      port: 5052
      targetPort: 5052

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rpcService.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.rpcService.name }}
  ports:
    - name: auth-rpc
      port: 8551
      targetPort: 8551
    - name: http-rpc
      port: 8545
      targetPort: 8545
    - name: ws-rpc
      port: 8546
      targetPort: 8546
    - name: p2p-tcp
      port: 30303
      targetPort: 30303
      protocol: TCP
    - name: p2p-udp
      port: 30303
      targetPort: 30303
      protocol: UDP
