apiVersion: v2
name: debugging
description: Deploy the Matthew Ahrenstein's standard debugging container along with the debugging namespace
type: application
version: 0.1.2
appVersion: "latest" # We always prefer running the latest debugging container
keywords:
  - Debugging
home: https://github.com/ahrenstein/docker-debugging
maintainers:
  - name: Route 1337 LLC
    url: https://www.route1337.com
deprecated: false
