apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}-mariadb
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}-mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}-mariadb
      annotations:
        {{- if .Values.mariadb.annotations }}
        {{- with .Values.mariadb.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      containers:
      - name: {{ .Values.serviceName }}-mariadb
        image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
        imagePullPolicy: Always
        ports:
          - name: mysql
            containerPort: 3306
            protocol: TCP
        env:
{{- if .Values.mariadb.dbSecret.manuallyCreatedSecret }}
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mariadb.dbSecret.manuallyCreatedSecret }}
                key: MYSQL_ROOT_PASSWORD
{{- else }}
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.serviceName }}-mariadb
                key: MYSQL_ROOT_PASSWORD
{{- end }}
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: {{ .Values.serviceName }}-db
            subPath: {{ .Values.nfs.nfsSubPath }}
      volumes:
        - name: {{ .Values.serviceName }}-db
          persistentVolumeClaim:
            claimName: {{ .Values.serviceName }}-mariadb-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}-mariadb
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.serviceName }}-mariadb
spec:
  selector:
    app: {{ .Values.serviceName }}-mariadb
  ports:
    - name: mysql
      port: 3306
