{{- if not .Values.phpipam.ipamSecret.manuallyCreatedSecret }}
  # ------------------- phpIPAM Secret ------------------- #
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.serviceName }}-phpipam
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: {{ .Values.phpipam.ipamSecret.secretStoreKind }}
    name: {{ .Values.phpipam.ipamSecret.secretStore }}
  target:
    creationPolicy: Owner
  data:
    - secretKey: IPAM_DATABASE_USER
      remoteRef:
        key: {{ .Values.phpipam.ipamSecret.secretName }}
        property: IPAM_DATABASE_USER
    - secretKey: IPAM_DATABASE_NAME
      remoteRef:
        key: {{ .Values.phpipam.ipamSecret.secretName }}
        property: IPAM_DATABASE_NAME
    - secretKey: IPAM_DATABASE_PASS
      remoteRef:
        key: {{ .Values.phpipam.ipamSecret.secretName }}
        property: IPAM_DATABASE_PASS
{{- end }}
{{- if not .Values.mariadb.dbSecret.manuallyCreatedSecret }}
# ------------------- MariaDB Secret ------------------- #
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.serviceName }}-mariadb
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: {{ .Values.mariadb.dbSecret.secretStoreKind }}
    name: {{ .Values.mariadb.dbSecret.secretStore }}
  target:
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: {{ .Values.mariadb.dbSecret.secretName }}
        property: MYSQL_ROOT_PASSWORD
{{- end }}
