{{- if not .Values.config.secret.manuallyCreatedSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.config.secret.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.config.secret.secretStore }}
    kind: {{ .Values.config.secret.secretStoreKind }}
  refreshInterval: "1h"
  target:
    name: {{ .Values.config.secret.secretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Template the connection string for NocoDB
        NC_DB: "mysql2://{{ .Values.config.serviceName }}-db:3306?u=root&p={{ `{{ .MYSQL_ROOT_PASSWORD }}` }}&d=nocodb"
        NC_AUTH_JWT_SECRET: "{{ `{{ .NC_AUTH_JWT_SECRET }}` }}"
        MYSQL_ROOT_PASSWORD: "{{ `{{ .MYSQL_ROOT_PASSWORD }}` }}"
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: {{ .Values.config.secret.secretName }}
        property: MYSQL_ROOT_PASSWORD
        decodingStrategy: None
        conversionStrategy: Default
        metadataPolicy: None
    - secretKey: NC_AUTH_JWT_SECRET
      remoteRef:
        key: {{ .Values.config.secret.secretName }}
        property: NC_AUTH_JWT_SECRET
        decodingStrategy: None
        conversionStrategy: Default
        metadataPolicy: None
{{- end }}
