---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.managedNetwork.serviceName }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: {{ .Values.secret.secretStoreKind }}
    name: {{ .Values.secret.secretStore }}
  target:
    creationPolicy: Owner
  data:
    - secretKey: cert
      remoteRef:
        key: {{ .Values.secret.secretName }}
        property: SSL_CERTIFICATE
        decodingStrategy: Base64
    - secretKey: key
      remoteRef:
        key: {{ .Values.secret.secretName }}
        property: SSL_KEY
        decodingStrategy: Base64
