namespace: cloudflared
clusterName: "1337-k8s"

secretsBackend: secretsManager

ingress:
  enabled: true
  replicas: 4
  metricsPort: 2000
  spreadPods: true
  consoleTokenSecret:
    secretName: 1337-k8s-cloudflare-ingress
    secretStore: 1password-prod
    secretStoreKind: ClusterSecretStore

warp:
  enabled: true
  replicas: 2
  metricsPort: 2000
  spreadPods: true
  consoleTokenSecret:
    secretName: 1337-k8s-cloudflare-warp
    secretStore: 1password-prod
    secretStoreKind: ClusterSecretStore

image:
  repository: cloudflare/cloudflared
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
