{{- if .Values.warp.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.clusterName }}-warp
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: cloudflared-warp
  replicas: {{ .Values.warp.replicas }}
  template:
    metadata:
      labels:
        app: cloudflared-warp
    spec:
      containers:
      - name: cloudflared-warp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        args:
        - tunnel
        - --metrics
        - "0.0.0.0:{{ .Values.warp.metricsPort }}"
        - --no-autoupdate
        - run
        - --token=$(CF_TOKEN)
        env:
          - name: CF_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.clusterName }}-warp
                key: console_token
        livenessProbe:
          httpGet:
            path: /ready
            port: {{ .Values.warp.metricsPort }}
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: {{ .Values.warp.metricsPort }}
            scheme: HTTP
        startupProbe:
          httpGet:
            path: /ready
            port: {{ .Values.warp.metricsPort }}
            scheme: HTTP
          failureThreshold: 60
          periodSeconds: 10
{{- end }}
