name: 'Basic Tests'

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Enter repo directory
        run: cd ~/work/helm-charts/helm-charts
      - name: Helm Installation
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
